version: '3'
services:
    web:
        build: .
        ports:
                - "3000:3000"
                - "8545:8545"
        volumes:
                - .:/HUD/:rw
        environment:
                - NODE_ENV=dev
        command:
                testrpc
      #  command: >
                #sh -c '
                #if test -d node_modules;
                #then
                    #echo node_modules_exists;
                #else
                    #cp -a /node_modules /HUD
                #fi &&
                #npm install 
                #'
